/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.github.sbstnc.example.otel

import org.springframework.boot.test.context.SpringBootTest
import spock.lang.Specification

@SpringBootTest
class AppTest extends Specification {
    def "context loads"() {
    }
}
